### ISSUE TITLE
Document `timeDifference` startegyOption

### ISSUE THREAD

**Issue by gr2m** [octokit/auth-app.js#199]
follow up to https://github.com/octokit/auth-app.js/pull/164. Looks like we implemented the option without documenting it.

@copperwall would you mind adding the documentation for the option?

**Comment by copperwall** [comment]
Oh yeah definitely!

**Comment by copperwall** [comment]
Hey @gr2m, I was looking into documenting this, but it looks like `timeDifference` lives in the `state` parameter to `auth` instead of `options` parameter that the user passes in. So it doesn't look like that option is available for the user to configure.

We could add it as an option and then initialize the state with the `timeDifference` from `options`, or leave it undocumented? What do you think?

**Comment by gr2m** [comment]
hmm sorry I found `timeDifference` defined in StrategyOptions:

https://github.com/octokit/auth-app.js/blob/90bc639ca0a3148768929ee119bbbab985616be8/src/types.ts#L76-L89

but it really should only be set on State instead. I just checked and everything still works if we do the change

```diff
diff --git a/src/types.ts b/src/types.ts
index 7093605..99ca9a3 100644
--- a/src/types.ts
+++ b/src/types.ts
@@ -81,7 +81,6 @@ export type StrategyOptions = {
   clientSecret?: string;
   request?: OctokitTypes.RequestInterface;
   cache?: Cache;
-  timeDifference?: number;
   log?: {
     warn: (message: string, additionalInfo?: object) => any;
     [key: string]: any;
@@ -125,6 +124,7 @@ export type State = StrategyOptions & {
   installationId?: number;
   request: OctokitTypes.RequestInterface;
   cache: Cache;
+  timeDifference?: number;
   log: {
     warn: (message: string, additionalInfo?: object) => any;
     [key: string]: any;
```

Would you like to send a PR for that?

**Comment by copperwall** [comment]
Ah yeah, I see what you mean. Thanks for pointing that out! I'll make a PR right now.
