### ISSUE TITLE
Throw error of unrecognized `type` in `.auth({ type })`

### ISSUE THREAD

**Issue by gr2m** [octokit/auth-app.js#216]
I just spend a significant amount of time debugging a problem that was ultimately caused by a space after `"installation "`:

```js
octokit.auth({ type: "installation " })
```

We should throw an error if a `type` is passed that is unknown. Otherwise it currently falls back to `oauth`, which is not what we want.

**Comment by oscard0m** [comment]
Hi @gr2m 

Taking a look into this.

Trying to reproduce it with TypeScript, the compiler complains about it:
https://codesandbox.io/s/octokit-auth-app-with-typo-lsg69

Do you have more details on how to reproduce this?

**Comment by gr2m** [comment]
I'd like to throw an Error in the code, and not rely on the TypeScript definitions. hen using the auth strategy with Octokit, the `octokit.auth()` method does currently not inherit the types

**Comment by oscard0m** [comment]
Drafted this PR (https://github.com/octokit/auth-app.js/pull/249) but at TS level does not have much sense since an invalid type is impossible to reach when using `@octokit/auth-app` package.

---

Checking at `@octokit/core` package, I found some `TODO`s which probably are the cause of the problem:
* https://github.com/octokit/core.js/blob/8d694c00a3a44c61c2fbb4d88e49e4a2d33fb50c/src/types.ts#L8-L11
* https://github.com/octokit/core.js/blob/8d694c00a3a44c61c2fbb4d88e49e4a2d33fb50c/src/index.ts#L119-L123
* https://github.com/octokit/core.js/blob/8d694c00a3a44c61c2fbb4d88e49e4a2d33fb50c/src/index.ts#L180-L181

And checking at `@octokit/types` seems we are not exposing AuthTypes. What we would need is:
https://github.com/octokit/auth-app.js/blob/f0086558a613c8615ef3519b2bd81aefda915c87/src/types.ts#L141-L144

Not sure how to proceed here:
* To place `AuthOptions` in `@octokit/types` (and `@octokit/auth-app` and `@octokit/core` consume them from there) (?)
* To add `@octokit/auth-app` as dependency for `@octokit/core` and consume `AuthOptions` directly (?)
* Any other option I'm not considering (?)

@gr2m

**Comment by gr2m** [comment]
> at TS level does not have much sense since an invalid type is impossible to reach when using `@octokit/auth-app` package.

That is a known limitation right now. See https://github.com/octokit/core.js/pull/32 and https://github.com/octokit/rest.js/issues/1562#issuecomment-582678977. It comes back to the idea of having a global `Octokit` namespace that plugins can extend, it's a bigger project. I want to create a high level issue for this for further discussion. This will also address the ability to define custom event webhooks, for example
